---
title: GMV Syncromatics ❤️ Hacktoberfest
timezone: UTC
collections:
  participants:
    title: Participants
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: "/hacktoberfest2018"
url: ''
markdown: kramdown
plugins:
- jekyll-feed
sass:
  sass_dir: _sass
